#!/usr/bin/env bash
# Pings IP address received as an argument 5 times.
# bash script to pass IP adress as arg
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS}

if [ $# -eq 0 ];then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
elif [ $# -gt 1];then
	echo "usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
else
	ping "$1" -c 5
fi
