#!/usr/bin/env bash
# Pings IP address received as an argument 5 times.
# bash script to pass IP adress as arg
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS}

if [ "$1" ]; then
    ping -c 5 "$1"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
