#!/usr/bin/env bash
# prints "To infinity and beyond indefinitely and sends a msg
# upon receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
while true; do
	echo To infinity and beyond
	sleep 2
done
