#!/usr/bin/env bash
# prints out username, user id and home directory for each line of /etc/passwd.

input="/etc/passwd"
while IFS= read -r l
do
    echo "$l" | cut -d':' --fields=1,3,6
done < "$input"
