#!/usr/bin/env bash
# repeats the time for 12 hours and 59 minutes.

HOUR=0
while [ $HOUR -lt 13 ]
do
    echo "Hour: $HOUR"
    MINS=1
    while [ $MINS -lt 60 ]
    do
        echo $MINS
	let MINS+=1
    done
    let HOUR+=1
done
